# campo_msg = '._1LbR4 > div:nth-child(2)' #main > footer > div._2BU3P.tm2tP.copyable-area > div > span:nth-child(2) > div > div._2lMWa > div.p3_M1 > div > div.fd365im1.to2l77zo.bbv8nyr4.mwp4sxku.gfz4du6o.ag5g9lrv > p
# campo_msg = "div.to2l77zo.gfz4du6o.ag5g9lrv.bze30y65.kao4egtt"
campo_msg_2 = ".div.fd365im1.to2l77zo.bbv8nyr4.mwp4sxku.gfz4du6o.ag5g9lrv"
campo_msg = "._3Uu1_"
campo_msg_css = ".p3_M1"
ok = "._20C5O"
campo_pesquisa = "div.to2l77zo.gfz4du6o.ag5g9lrv.bze30y65.kao4egtt.qh0vvdkp"
nova_conversa = "._3yZPA"
Scanme = "._2UwZ_ > canvas:nth-child(3)"
desconectar = ".tvf2evcx"
botao_ok_xpath = "/html/body/div[1]/div[1]/span[2]/div[1]/span/div[1]/div/div/div/div/div[2]/div/div/div"
nome_xpath = '_1Oe6M'
nome_CSS = 'div._8nE1Y'
nome_CSS1 = '._21S-L'
nome_CSS2 = "._3vPI2"
pesquisa_contato = '/html/body/div[1]/div[1]/div[1]/div[3]/div/div[1]/div/label/div/div[2]'

barra = "#main > header > div._24-Ff > div > div > span"
barra_superior = '._3W2ap'
botao_enviar_imagem = "._3wFFT"
bloqueado = '/html/body/div[1]/div/div/div[4]/div/footer/div/text()'